In [2]:
# what is the best way in np to get a list of 20 unique integer?
import numpy as np

rand_ints = np.random.randint(1, 100, 20)  # choose 20 random integers between 1 and 100
unique_ints = np.unique(rand_ints)  # get only the unique integers from the list

print(unique_ints) 

[ 7 12 14 17 20 22 29 37 38 52 53 57 58 64 76 79 81 96]


# Exercises with NumPy

1. Get the 10-day forecast for your city. Create two NumPy arrays -- `highs` with the expected high temps and `lows` with the expected low temps.
2. Find the mean high temp in the coming days.
3. Find the std for high temps, as well.
4. If you entered the temperature in Fahrenheit, convert the temperature to Celsius. (If you used Celsius, convert to Fahrenheight.) Do this for each answer so it displays a F and C result.
5. Calculate the mean difference between highs and lows in the coming days.

In [13]:
import numpy as np

# hypothetical forecast for the week of May 25th in San Francisco
highs = np.array([67, 68, 69, 68, 63, 62, 64, 67, 68, 68])
lows = np.array([55, 55, 56, 54, 52, 51, 54, 54, 55, 55])

mean_highs = np.mean(highs)
print(f"Mean high temperature: {mean_highs} F, {(mean_highs-32)*5/9:.1f} C")

std_highs = np.std(highs)
print(f"High temperature standard deviation: {std_highs:.2f} F, {(std_highs)*5/9:.2f} C")

def convert_temp(temp_array, method):
    """NP array conversion

    Args:
        temp_array (np.array): temps
        method (string): FtoC or CtoF

    Returns:
        np.array: result temps
    """
    if method == "FtoC":
        return (temp_array - 32) * 5/9
    elif method == "CtoF":
        return (temp_array * 9/5) + 32
    else:
        return 0

# converting highs array to Celsius
highs_C = convert_temp(highs, "FtoC")
low_c = convert_temp(lows, "FtoC")

print(f"High temperatures in Celsius: {highs_C}, in Fahrenheit: {convert_temp(highs_C, 'CtoF')}")
print(f"Low temperatures in Celsius: {low_c}, in Fahrenheit: {convert_temp(low_c, 'CtoF')}")

mean_diff = np.mean(highs - lows)
print(f"Mean temperature difference: {mean_diff} F, {convert_temp(mean_diff, 'FtoC'):.1f} C")

Mean high temperature: 66.4 F, 19.1 C
High temperature standard deviation: 2.33 F, 1.30 C
High temperatures in Celsius: [19.44444444 20.         20.55555556 20.         17.22222222 16.66666667
 17.77777778 19.44444444 20.         20.        ], in Fahrenheit: [67. 68. 69. 68. 63. 62. 64. 67. 68. 68.]
Low temperatures in Celsius: [12.77777778 12.77777778 13.33333333 12.22222222 11.11111111 10.55555556
 12.22222222 12.22222222 12.77777778 12.77777778], in Fahrenheit: [55. 55. 56. 54. 52. 51. 54. 54. 55. 55.]
Mean temperature difference: 12.3 F, -10.9 C


# Exercises:


1. Create an array of 20 random integers from 0 to 100.
2. Find the largest even number.
3. Find the mean of the odd numbers.
4. Find items that are less than the mean.
5. Find items less than the mean-std.

In [23]:
# %%timeit
import random
import statistics

# 1. Create an array of 20 random integers from 0 to 100.
arr = [random.randint(0, 100) for i in range(20)]
print(f"Array: {arr}")

# 2. Find the largest even number.
even_nums = [num for num in arr if num % 2 == 0]
largest_even = max(even_nums)
print(f"Largest even number: {largest_even}")

# 3. Find the mean of the odd numbers.
odd_nums = [num for num in arr if num % 2 != 0]
mean_odd = statistics.mean(odd_nums)
print(f"Mean of odd numbers: {mean_odd}")

# 4. Find items that are less than the mean.
less_than_mean = [num for num in arr if num < statistics.mean(arr)]
print(f"Items less than the mean: {less_than_mean}")

# 5. Find items less than the mean-std.
less_than_mean_std = [num for num in arr if num < statistics.mean(arr) - statistics.stdev(arr)]
print(f"Items less than the mean-std: {less_than_mean_std}")

Array: [41, 52, 81, 89, 91, 76, 91, 20, 27, 65, 11, 77, 46, 8, 10, 50, 82, 41, 90, 9]
Largest even number: 90
Mean of odd numbers: 56.63636363636363
Items less than the mean: [41, 52, 20, 27, 11, 46, 8, 10, 50, 41, 9]
Items less than the mean-std: [20, 11, 8, 10, 9]


In [24]:
# %%timeit
import nu
# 4. Find items that are less than the mean.
below_mean = arr[arr < np.mean(arr)]
print(f"Items less than the mean: {below_mean}")

# 5. Find items less than the mean-std.
below_mean_std = arr[arr < np.mmpy as np

# 1. Create an np array of 20 random integers from 0 to 100.
arr = np.random.randint(0, 100, 20)
print(f"Array: {arr}")

# 2. Find the largest even number.
even_nums = arr[arr % 2 == 0]
largest_even = np.max(even_nums)
print(f"Largest even number: {largest_even}")

# 3. Find the mean of the odd numbers.
odd_nums = arr[arr % 2 != 0]
odd_mean = np.mean(odd_nums)
print(f"Mean of odd numbers: {odd_mean}")
ean(arr) - np.std(arr)]
print(f"Items less than the mean-std: {below_mean_std}")

Array: [17 15  0 11 84 98 52 51 82 84 28 28 18 23 72  8 61  3 97 88]
Largest even number: 98
Mean of odd numbers: 34.75
Items less than the mean: [17 15  0 11 28 28 18 23  8  3]
Items less than the mean-std: [ 0 11  8  3]


In [33]:
a = np.random.randint(1, 100, 20) 
print(a)
print(a[(a % 2 == 0) & (a < a.mean())])

[60 29 93 65 14 91 98 55 18 31 89 25 32 63  9 83  5 16 98 41]
[14 18 32 16]


# NP Exercises 

1. Create an array of 20 random integers from 1-1,000.
2. What's the smallest even number greater than the mean?
3. Show all numbers that are either < mean-std  or > mean+std.
4. Show odd numbers < mean, and even numbers > mean.

In [35]:
import numpy as np

# Create array of 20 random integers from 1-1,000
arr = np.random.randint(1, 1001, size=20)

# Calculate mean and standard deviation
mean = np.mean(arr)
std = np.std(arr)

# Find smallest even number greater than the mean
even_nums = arr[arr % 2 == 0]
smallest_even = np.min(even_nums[even_nums > mean])

# Show all numbers that are either < mean-std or > mean+std
outside_mean_std = arr[(arr < mean - std) | (arr > mean + std)]

# Show odd numbers < mean, and even numbers > mean
odds_below_mean = arr[(arr < mean) & (arr % 2 != 0)]
evens_above_mean = arr[(arr > mean) & (arr % 2 == 0)]

# Print results
print(f"Array: {arr}")
print(f"Mean: {mean:.2f}")
print(f"Standard Deviation: {std:.2f}")
print(f"Smallest even number greater than the mean: {smallest_even}")
print(f"Numbers less than mean-std or greater than mean+std: {outside_mean_std}")
print(f"Odd numbers less than mean: {odds_below_mean}")
print(f"Even numbers greater than mean: {evens_above_mean}")

Array: [912 462 336 183 236 580 146 479 394 454 125 607 496 877 432 262 622 595
 337 248]
Mean: 439.15
Standard Deviation: 213.21
Smallest even number greater than the mean: 454
Numbers less than mean-std or greater than mean+std: [912 183 146 125 877]
Odd numbers less than mean: [183 125 337]
Even numbers greater than mean: [912 462 580 454 496 622]


The dtype ranges for numpy are as follows:

1. int8: Range from -128 to 127
2. uint8: Range from 0 to 255
3. int16: Range from -32768 to 32767
4. uint16: Range from 0 to 65535
5. int32: Range from -2147483648 to 2147483647
6. uint32: Range from 0 to 4294967295
7. int64: Range from -9223372036854775808 to 9223372036854775807
8. uint64: Range from 0 to 18446744073709551615
9. float16: Range from -65504 to 65504
10. float32: Range from -3.4028235e+38 to 3.4028235e+38
11. float64: Range from -1.7976931348623157e+308 to 1.7976931348623157e+308
12. complex64: Range from (-3.4028235e+38 - 3.4028235e+38j) to (3.4028235e+38 + 3.4028235e+38j)
13. complex128: Range from (-1.7976931348623157e+308 - 1.7976931348623157e+308j) to (1.7976931348623157e+308 + 1.7976931348623157e+308j)

# Exercise: `astype` and friends

 

1. Create an array of 20 *floats* between 0 and 1,000.
2. Find the mean of those floats whose integer part is even.  So 25.3 would be considered odd, but 28.7 would be considered event.

In [41]:
import numpy as np

# Create array of 20 floats between 0 and 1000
arr = np.random.uniform(0, 1000, 20)
print(arr)

evens = arr[arr.astype(int) % 2 == 0]
print(evens)
# Find mean of floats whose integer part is even
even_mean = np.mean(evens)

print(even_mean)

[956.47158011 775.43852613 702.3353016  591.42613725 784.56147642
 191.27873378  23.88482591 912.13840719 781.14225862 690.78677547
  88.42283278 598.95300431 786.88411491 767.7821504  311.76184639
 527.84996674 695.15906081 482.6118631  996.53638308 970.4114387 ]
[956.47158011 702.3353016  784.56147642 912.13840719 690.78677547
  88.42283278 598.95300431 786.88411491 482.6118631  996.53638308
 970.4114387 ]
724.5557434244472


# Exercise: Working with `nan`

 

1. Create a NumPy array of 20 integers from 0-100.
2. Calculate the mean (which is a float).
3. Replace all values < mean-std or > mean+std with nan. (You might need to change the dtype of the array here.)

In [45]:
import numpy as np

# 1. Create NumPy array of 20 integers from 0 to 100
arr = np.random.randint(low=0, high=100, size=20)
arr
# 2. Calculate the mean
mean = np.mean(arr)

# 3. Replace values < mean-std or > mean+std with nan
std = np.std(arr)
arr = arr.astype(float)  # Change dtype to float so we can replace with nan
arr[(arr < mean - std) | (arr > mean + std)] = np.nan

print(arr)

[78. 24. nan 92. nan 61. nan nan 91. 77. 91. 62. 96. nan 28. nan nan 95.
 74. 90.]


Homework Solutions

In Python using numpy solve for: 
Input :
N = 7, K = 2
A[] = {1, 7, 4, 3, 4, 8, 7}
Output :
4
Explanation:
Both 7 and 4 occur 2 times.
But 4 is first that occurs 2 times
As at index = 4, 4 has occurred 
atleast 2 times whereas at index = 6,
7 has occurred atleast 2 times.

In [ ]:
import numpy as np

def firstElementKTime(A, K, N):
    """
    Find the value that occurs K times in the first N elements of A.
    """
    # make sure N is not larger than the array size
    N = min(N, len(A))
    
    # select the first N elements of A
    A = A[:N]
    print(A)
    # create a boolean mask that marks the elements that occur at least K times
    mask = np.sum(A.reshape(-1, 1) == A, axis=0) >= K
    print(mask)
    # find the index of the first occurrence that satisfies the condition
    index = np.argmax(mask)
    
    # return the value at that index
    return A[index]

In [ ]:
import numpy as np

def firstElementKTime(A, N, K):
    counts = np.array([np.sum(A == i) for i in A],dtype=object) # count occurrences of each unique element
    print(counts)

    matches = np.argwhere(counts == K).flatten() # find indices where count equals K
    print(matches)
    if len(matches) == 0:
        return -1
    else:
        return np.min(matches) # find first index of element that occurs K times

In [ ]:
# example
A = np.array([1, 7, 4, 3, 4, 8, 7])
print(A)
N = 7
K = 2

print(firstElementKTime(A, K, N)) 

Using numpy and broadcast I need to be able to find the find the value of an integer in an array of N size, The user will pass the array, the number of indexes/size they wish to search, and the count of occurrence they want to find in the array. So if I passed in K as 2 meaning the number of occurrences is 2 and an array A = np.array([1, 7, 4, 3, 4, 8, 7]) it would return the value 4 since the index 3 is repeated twice first before 7 is repeated twice. N will only search the array up to that index so in the above example if I put N= 3 then it would only compare the first three elements. If K is not found then it returns -1. Again, If I mark k as 2 and N as 7 then the answer should be 4 not 7. because K is satisfied first by the 4 in index four where 7 is not satisfied until index 6. Meaning I want to return the index of the first iteration of K that is satisfied. 